import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const businessReport: ThemePreset = {
  id: "business-report",
  name: "商务报告",
  description: "麦肯锡咨询报告风格，沉稳深蓝、条理清晰与专业研报排印",
  tags: ["商务", "麦肯锡", "咨询报告", "深蓝", "专业", "战略规划"],
  cardGradient: ["#eff6ff", "#bfdbfe"],
  containerVariant: "default",
  banner: {
    type: "none",
  },
  h2Decoration: "report-pill",
  quoteStyle: "report-takeaway",
  dividerText: "─────── ❖ ───────",
  markHighlight: {
    background: "rgba(30, 58, 138, 0.12)",
    borderBottom: "2px solid #1e3a8a",
    color: "#1e3a8a",
    padding: "0 4px",
    fontWeight: 700,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 400,
    fontSize: "15.5px",
    lineHeight: "1.9",
    color: "#1e293b",
    backgroundColor: "#ffffff",
    maxWidth: "720px",
    margin: "0 auto",
    padding: "50px 42px",
    borderRadius: "10px",
    boxShadow: "0 20px 45px -12px rgba(15, 23, 42, 0.08), 0 0 0 1px rgba(0, 0, 0, 0.04)",
  },
  elements: {
    h1: {
      fontSize: "28px",
      fontWeight: 800,
      color: "#1e3a8a",
      marginBottom: "30px",
      letterSpacing: "-0.3px",
      lineHeight: "1.75",
      paddingBottom: "16px",
      borderBottom: "2.5px solid #1e3a8a",
    },
    h2: {
      fontSize: "19px",
      fontWeight: 700,
      marginTop: "42px",
      marginBottom: "20px",
      color: "#1e3a8a",
    },
    h3: {
      fontSize: "16.5px",
      fontWeight: 600,
      marginTop: "28px",
      marginBottom: "12px",
      color: "#2563eb",
    },
    h4: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#1e3a8a",
    },
    h5: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#1e3a8a",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#1e3a8a",
    },
    p: {
      marginTop: "0",
      marginBottom: "20px",
      fontSize: "15.5px",
      textAlign: "justify",
      color: "#334155",
      letterSpacing: "0.2px",
      lineHeight: "1.9",
    },
    blockquote: {
      backgroundColor: "#f0f7ff",
      borderLeft: "3.5px solid #1e3a8a",
      padding: "18px 22px",
      margin: "26px 0",
      borderRadius: "0 8px 8px 0",
      color: "#1e293b",
      fontSize: "15px",
      lineHeight: "1.85",
    },
    ul: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "disc",
    },
    ol: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      fontSize: "15px",
      color: "#334155",
    },
    a: {
      color: "#1e3a8a",
      textDecoration: "underline",
      textUnderlineOffset: "3px",
      fontWeight: 600,
    },
    strong: {
      color: "#0f172a",
      fontWeight: 700,
    },
    em: {
      fontStyle: "italic",
    },
    code: {
      backgroundColor: "#f1f5f9",
      color: "#1e3a8a",
      padding: "2px 6px",
      borderRadius: "4px",
      fontSize: "0.88em",
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      border: "1px solid #e2e8f0",
    },
    pre: {
      backgroundColor: "#0f172a",
      color: "#f8fafc",
      padding: "20px 24px",
      borderRadius: "8px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.75",
      margin: "24px 0",
    },
    img: {
      maxWidth: "100%",
      borderRadius: "6px",
      margin: "30px auto",
      display: "block",
      border: "1px solid #e2e8f0",
      boxShadow: "0 6px 20px rgba(0, 0, 0, 0.06)",
    },
    hr: {
      border: "none",
      borderTop: "1.5px solid #e2e8f0",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "26px 0",
      fontSize: "14.5px",
    },
    th: {
      padding: "12px 16px",
      backgroundColor: "#1e3a8a",
      color: "#ffffff",
      fontWeight: 700,
      textAlign: "left",
      borderRight: "1px solid #2563eb",
    },
    td: {
      padding: "11px 16px",
      borderBottom: "1px solid #e2e8f0",
    },
  },
};
