import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const classicAcademic: ThemePreset = {
  id: "classic-academic",
  name: "经典学术",
  description: "权威期刊论文规范，正统三线表、宋体沉稳与首行两字符缩进",
  tags: ["学术", "论文", "三线表", "宋体", "严谨规范", "期刊"],
  cardGradient: ["#f5f5f4", "#e7e5e4"],
  containerVariant: "academic-paper",
  banner: {
    type: "none",
  },
  h2Decoration: "academic-bracket",
  quoteStyle: "academic-abstract",
  dividerText: "─ ─ ─   ❖   ─ ─ ─",
  markHighlight: {
    background: "#e7e5e4",
    padding: "0 3px",
    color: "#0c0a09",
    fontWeight: 700,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "2.1",
    color: "#1c1917",
    backgroundColor: "#ffffff",
    maxWidth: "720px",
    margin: "0 auto",
    padding: "52px 42px",
    boxShadow: "0 20px 45px -10px rgba(0, 0, 0, 0.06), 0 0 0 1px rgba(0, 0, 0, 0.03)",
    borderRadius: "8px",
  },
  elements: {
    h1: {
      fontSize: "28px",
      fontWeight: 800,
      textAlign: "center",
      marginBottom: "32px",
      color: "#0c0a09",
      letterSpacing: "2.5px",
      lineHeight: "1.75",
      paddingBottom: "16px",
      borderBottom: "2px solid #1c1917",
    },
    h2: {
      fontSize: "19px",
      fontWeight: 700,
      marginTop: "44px",
      marginBottom: "20px",
      color: "#1c1917",
      letterSpacing: "0.5px",
    },
    h3: {
      fontSize: "16.5px",
      fontWeight: 700,
      marginTop: "28px",
      marginBottom: "12px",
      color: "#292524",
    },
    h4: {
      fontSize: "16px",
      fontWeight: 700,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#292524",
    },
    h5: {
      fontSize: "15.5px",
      fontWeight: 700,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#292524",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 700,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#292524",
    },
    p: {
      marginTop: "0",
      textIndent: "2em",
      marginBottom: "20px",
      textAlign: "justify",
      fontSize: "16px",
      letterSpacing: "0.2px",
      color: "#1c1917",
      lineHeight: "2.1",
    },
    blockquote: {
      margin: "24px 1.5em",
      padding: "18px 24px",
      backgroundColor: "#fafaf9",
      borderLeft: "3.5px solid #78716c",
      color: "#292524",
      fontSize: "15px",
      lineHeight: "1.9",
      fontStyle: "italic",
      borderRadius: "0 6px 6px 0",
    },
    ul: {
      paddingLeft: "2.5em",
      marginBottom: "20px",
      listStyleType: "circle",
    },
    ol: {
      paddingLeft: "2.5em",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      color: "#1c1917",
      fontSize: "15px",
    },
    a: {
      color: "#1c1917",
      textDecoration: "underline",
      textUnderlineOffset: "3px",
      fontWeight: 600,
    },
    strong: {
      fontWeight: 700,
      color: "#0c0a09",
    },
    em: {
      fontStyle: "italic",
    },
    code: {
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      backgroundColor: "#f5f5f4",
      color: "#1c1917",
      padding: "2px 6px",
      fontSize: "0.88em",
      border: "1px solid #e7e5e4",
      borderRadius: "3px",
    },
    pre: {
      backgroundColor: "#1c1917",
      color: "#f5f5f4",
      padding: "20px 24px",
      borderRadius: "6px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.75",
      margin: "26px 0",
    },
    img: {
      maxWidth: "100%",
      margin: "32px auto",
      display: "block",
      borderRadius: "2px",
      border: "1px solid #e2e8f0",
      padding: "4px",
      backgroundColor: "#ffffff",
    },
    hr: {
      border: "none",
      borderTop: "1px solid #d6d3d1",
      margin: "36px 0",
    },
    // 严格的三线表（顶线、栏目线、底线）
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "28px 0",
      borderTop: "2px solid #1c1917",
      borderBottom: "2px solid #1c1917",
      fontSize: "14.5px",
    },
    th: {
      padding: "11px 16px",
      borderBottom: "1px solid #78716c",
      color: "#0c0a09",
      fontWeight: 700,
      textAlign: "left",
      backgroundColor: "#ffffff",
    },
    td: {
      padding: "10px 16px",
      borderBottom: "none",
      color: "#292524",
    },
  },
};
