import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const curatorGallery: ThemePreset = {
  id: "curator-gallery",
  name: "艺术策展",
  description: "国际画廊展讯与策展导览，黑金双细线框与艺术沉浸感",
  tags: ["策展", "画廊", "黑金", "艺术展讯", "现代美学", "高端专栏"],
  cardGradient: ["#1c1917", "#292524"],
  containerVariant: "default",
  banner: {
    type: "none",
  },
  h2Decoration: "gallery-line",
  quoteStyle: "gallery-clean",
  dividerText: "── ✦ ──",
  markHighlight: {
    background: "rgba(217, 119, 6, 0.25)",
    borderBottom: "1.5px solid #d97706",
    color: "#f59e0b",
    padding: "0 4px",
    fontWeight: 600,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 300,
    fontSize: "15.5px",
    lineHeight: "2.1",
    color: "#d6d3d1",
    backgroundColor: "#171513",
    maxWidth: "720px",
    margin: "0 auto",
    padding: "52px 42px",
    borderRadius: "8px",
    border: "1px solid #332d29",
    boxShadow: "0 25px 50px -15px rgba(0, 0, 0, 0.8), 0 0 0 1px rgba(217, 119, 6, 0.15)",
  },
  elements: {
    h1: {
      fontSize: "30px",
      fontWeight: 600,
      textAlign: "center",
      marginBottom: "32px",
      color: "#f59e0b",
      letterSpacing: "4px",
      lineHeight: "1.75",
      paddingBottom: "18px",
      borderBottom: "1px solid #78350f",
    },
    h2: {
      fontSize: "19px",
      fontWeight: 700,
      marginTop: "44px",
      marginBottom: "20px",
      color: "#fbbf24",
      textAlign: "center",
      letterSpacing: "3px",
    },
    h3: {
      fontSize: "16.5px",
      fontWeight: 600,
      marginTop: "30px",
      marginBottom: "12px",
      color: "#f59e0b",
      paddingLeft: "10px",
      borderLeft: "3px solid #d97706",
    },
    h4: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#fbbf24",
    },
    h5: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#fbbf24",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#fbbf24",
    },
    p: {
      marginTop: "0",
      marginBottom: "20px",
      textAlign: "justify",
      fontSize: "15.5px",
      letterSpacing: "0.4px",
      color: "#a8a29e",
      lineHeight: "2.1",
    },
    blockquote: {
      backgroundColor: "rgba(245, 158, 11, 0.05)",
      borderLeft: "3.5px solid #d97706",
      padding: "20px 26px",
      margin: "28px 0",
      borderRadius: "0 6px 6px 0",
      color: "#e7e5e4",
      fontSize: "15px",
      lineHeight: "1.9",
    },
    ul: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "circle",
    },
    ol: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      color: "#a8a29e",
      fontSize: "15px",
    },
    a: {
      color: "#f59e0b",
      textDecoration: "underline",
      textUnderlineOffset: "3px",
      fontWeight: 600,
    },
    strong: {
      color: "#fbbf24",
      fontWeight: 600,
    },
    em: {
      fontStyle: "italic",
      color: "#f59e0b",
    },
    code: {
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      backgroundColor: "#292524",
      color: "#fbbf24",
      padding: "2px 7px",
      borderRadius: "3px",
      fontSize: "0.88em",
      border: "1px solid #44403c",
    },
    pre: {
      backgroundColor: "#0c0a09",
      color: "#f5f5f4",
      padding: "22px 26px",
      borderRadius: "6px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.75",
      margin: "26px 0",
      border: "1px solid #292524",
    },
    img: {
      maxWidth: "100%",
      borderRadius: "4px",
      margin: "32px auto",
      display: "block",
      border: "1px solid #44403c",
      boxShadow: "0 8px 30px rgba(0, 0, 0, 0.5)",
    },
    hr: {
      border: "none",
      borderTop: "1px solid #44403c",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "26px 0",
      fontSize: "14.5px",
      border: "1px solid #44403c",
    },
    th: {
      padding: "12px 16px",
      backgroundColor: "#292524",
      color: "#fbbf24",
      fontWeight: 700,
      textAlign: "left",
      borderBottom: "2px solid #78350f",
    },
    td: {
      padding: "11px 16px",
      borderBottom: "1px solid #292524",
      color: "#a8a29e",
    },
  },
};
