import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const darkGeek: ThemePreset = {
  id: "dark-geek",
  name: "暗色极客",
  description: "GitHub 与 Linear 曜黑极客美学，天青与荧光绿代码质感",
  tags: ["极客", "终端", "暗黑", "开发者", "天青蓝", "代码美学"],
  cardGradient: ["#1e293b", "#0f172a"],
  containerVariant: "terminal-window",
  banner: {
    type: "none",
  },
  h2Decoration: "terminal-prompt",
  quoteStyle: "terminal-box",
  dividerText: "// ---------------------------------------------------- //",
  markHighlight: {
    background: "rgba(34, 197, 94, 0.22)",
    borderBottom: "2px solid #22c55e",
    color: "#4ade80",
    padding: "0 5px",
    borderRadius: "2px",
    fontWeight: 700,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 500,
    fontSize: "15px",
    lineHeight: "1.9",
    color: "#cbd5e1",
    backgroundColor: "#0d1117",
    maxWidth: "720px",
    margin: "0 auto",
    padding: "50px 40px",
    borderRadius: "12px",
    border: "1px solid #30363d",
    boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.7), 0 0 0 1px rgba(255, 255, 255, 0.05)",
  },
  elements: {
    h1: {
      fontSize: "28px",
      fontWeight: 800,
      color: "#38bdf8",
      lineHeight: "1.75",
      marginBottom: "30px",
      letterSpacing: "-0.5px",
      paddingBottom: "16px",
      borderBottom: "1px solid #30363d",
    },
    h2: {
      fontSize: "19px",
      fontWeight: 700,
      color: "#38bdf8",
      marginTop: "44px",
      marginBottom: "20px",
    },
    h3: {
      fontSize: "16.5px",
      fontWeight: 600,
      color: "#a78bfa",
      marginTop: "28px",
      marginBottom: "12px",
    },
    h4: {
      fontSize: "15px",
      fontWeight: 600,
      color: "#94a3b8",
      marginTop: "20px",
      marginBottom: "8px",
    },
    h5: {
      fontSize: "15px",
      fontWeight: 600,
      color: "#94a3b8",
      marginTop: "20px",
      marginBottom: "8px",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 600,
      color: "#94a3b8",
      marginTop: "20px",
      marginBottom: "8px",
    },
    p: {
      marginTop: "0",
      marginBottom: "20px",
      color: "#cbd5e1",
      textAlign: "left",
      letterSpacing: "0.2px",
      lineHeight: "1.9",
      fontSize: "15px",
    },
    blockquote: {
      backgroundColor: "rgba(56, 189, 248, 0.05)",
      borderLeft: "3.5px solid #38bdf8",
      padding: "18px 22px",
      margin: "26px 0",
      borderRadius: "0 6px 6px 0",
      color: "#93c5fd",
      fontSize: "14.5px",
      lineHeight: "1.85",
    },
    ul: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "square",
    },
    ol: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      color: "#cbd5e1",
      fontSize: "14.5px",
    },
    a: {
      color: "#38bdf8",
      textDecoration: "underline",
      textUnderlineOffset: "3px",
      fontWeight: 600,
    },
    strong: {
      color: "#f8fafc",
      fontWeight: 700,
    },
    em: {
      fontStyle: "italic",
      color: "#93c5fd",
    },
    code: {
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      backgroundColor: "#161b22",
      color: "#38bdf8",
      padding: "2px 7px",
      borderRadius: "4px",
      fontSize: "0.9em",
      border: "1px solid #30363d",
    },
    pre: {
      backgroundColor: "#161b22",
      color: "#f0f6fc",
      padding: "20px 24px",
      borderRadius: "8px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.75",
      margin: "24px 0",
      border: "1px solid #30363d",
    },
    img: {
      maxWidth: "100%",
      borderRadius: "8px",
      margin: "30px auto",
      display: "block",
      border: "1px solid #30363d",
      boxShadow: "0 0 20px rgba(56, 189, 248, 0.12)",
    },
    hr: {
      border: "none",
      borderTop: "1px solid #30363d",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "26px 0",
      fontSize: "14px",
      border: "1px solid #30363d",
    },
    th: {
      padding: "12px 16px",
      backgroundColor: "#161b22",
      color: "#38bdf8",
      fontWeight: 700,
      textAlign: "left",
      borderBottom: "1px solid #30363d",
    },
    td: {
      padding: "11px 16px",
      borderBottom: "1px solid #21262d",
      color: "#cbd5e1",
    },
  },
};
