import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const freshMint: ThemePreset = {
  id: "fresh-mint",
  name: "薄荷青柠",
  description: "清凉薄荷青与明快柠檬黄，充满清晨元气与健康活力的年轻排版",
  tags: ["薄荷青", "柠檬黄", "元气活力", "清爽微甜", "健康生活", "效率分享"],
  cardGradient: ["#ecfdf5", "#fef9c3"],
  containerVariant: "default",
  banner: {
    type: "none",
  },
  h2Decoration: "mint-capsule",
  quoteStyle: "mint-bubble",
  dividerText: "✦ ── 🍋 ── ✦",
  markHighlight: {
    background: "linear-gradient(to top, rgba(167, 243, 208, 0.7) 45%, transparent 45%)",
    padding: "0 4px",
    borderRadius: "2px",
    color: "#065f46",
    fontWeight: 600,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 300,
    fontSize: "15.5px",
    lineHeight: "1.9",
    color: "#1f2937",
    backgroundColor: "#ffffff",
    maxWidth: "680px",
    margin: "0 auto",
    padding: "48px 36px",
    borderRadius: "12px",
    boxShadow: "0 15px 35px -5px rgba(16, 185, 129, 0.08), 0 0 0 1px rgba(0, 0, 0, 0.02)",
  },
  elements: {
    h1: {
      fontSize: "27px",
      fontWeight: 600,
      textAlign: "center",
      marginBottom: "30px",
      color: "#0d9488",
      letterSpacing: "0.5px",
      lineHeight: "1.7",
      paddingBottom: "14px",
      borderBottom: "1.5px solid #99f6e4",
    },
    h2: {
      fontSize: "18.5px",
      fontWeight: 700,
      marginTop: "42px",
      marginBottom: "18px",
      color: "#0f766e",
      display: "flex",
      alignItems: "center",
    },
    h3: {
      fontSize: "16.5px",
      fontWeight: 600,
      marginTop: "26px",
      marginBottom: "12px",
      color: "#0d9488",
      paddingLeft: "10px",
      borderLeft: "3.5px solid #14b8a6",
    },
    h4: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#0f766e",
    },
    h5: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#0f766e",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#0f766e",
    },
    p: {
      marginTop: "0",
      marginBottom: "18px",
      fontSize: "15.5px",
      textAlign: "justify",
      letterSpacing: "0.3px",
      color: "#374151",
      lineHeight: "1.9",
    },
    blockquote: {
      backgroundColor: "rgba(13, 148, 136, 0.06)",
      borderLeft: "3.5px solid #0d9488",
      padding: "18px 22px",
      margin: "24px 0",
      borderRadius: "0 8px 8px 0",
      color: "#0f766e",
      fontSize: "15px",
      lineHeight: "1.85",
    },
    ul: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "circle",
    },
    ol: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      fontSize: "15px",
      color: "#374151",
    },
    a: {
      color: "#0d9488",
      textDecoration: "underline",
      textUnderlineOffset: "3px",
      fontWeight: 600,
    },
    strong: {
      color: "#065f46",
      fontWeight: 600,
    },
    em: {
      fontStyle: "italic",
      color: "#0d9488",
    },
    code: {
      backgroundColor: "#ccfbf1",
      color: "#0f766e",
      padding: "2px 7px",
      borderRadius: "4px",
      fontSize: "0.88em",
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
    },
    pre: {
      backgroundColor: "#134e4a",
      color: "#f0fdfa",
      padding: "20px 24px",
      borderRadius: "10px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.7",
      margin: "24px 0",
    },
    img: {
      maxWidth: "100%",
      borderRadius: "10px",
      margin: "28px auto",
      display: "block",
      boxShadow: "0 6px 20px rgba(13, 148, 136, 0.08)",
    },
    hr: {
      border: "none",
      borderTop: "1.5px dashed #99f6e4",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "24px 0",
      fontSize: "14.5px",
    },
    th: {
      padding: "12px 16px",
      backgroundColor: "#ccfbf1",
      color: "#0f766e",
      fontWeight: 700,
      textAlign: "left",
      borderBottom: "2px solid #0d9488",
    },
    td: {
      padding: "11px 16px",
      borderBottom: "1px solid #e5e7eb",
    },
  },
};
