import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const literaryFresh: ThemePreset = {
  id: "literary-fresh",
  name: "文艺清新",
  description: "日系静谧散文，莫兰迪鼠尾草绿、两端破折号与诗意呼吸感",
  tags: ["文艺", "散文", "莫兰迪绿", "呼吸感", "诗意", "日系随笔"],
  cardGradient: ["#f0fdf4", "#dcfce7"],
  containerVariant: "default",
  banner: {
    type: "none",
  },
  h2Decoration: "literary-dash",
  quoteStyle: "literary-minimal",
  dividerText: "·   ·   ·",
  markHighlight: {
    background: "rgba(187, 247, 208, 0.5)",
    padding: "0 4px",
    color: "#166534",
    fontWeight: 600,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 300,
    fontSize: "16px",
    lineHeight: "2.2",
    color: "#374334",
    backgroundColor: "#fafaf6",
    maxWidth: "700px",
    margin: "0 auto",
    padding: "52px 42px",
    boxShadow: "0 15px 35px rgba(60, 70, 50, 0.05), 0 0 0 1px rgba(60, 70, 50, 0.03)",
    borderRadius: "10px",
  },
  elements: {
    h1: {
      fontSize: "26px",
      fontWeight: 600,
      textAlign: "center",
      color: "#283618",
      marginBottom: "36px",
      letterSpacing: "5px",
      lineHeight: "1.7",
      paddingBottom: "16px",
      borderBottom: "1px solid #d5dec6",
    },
    h2: {
      fontSize: "19px",
      fontWeight: 600,
      marginTop: "46px",
      marginBottom: "22px",
      color: "#384725",
      textAlign: "center",
      letterSpacing: "3.5px",
    },
    h3: {
      fontSize: "16.5px",
      fontWeight: 600,
      marginTop: "28px",
      marginBottom: "12px",
      color: "#465830",
      letterSpacing: "1.5px",
    },
    h4: {
      fontSize: "15px",
      fontWeight: 500,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#465830",
    },
    h5: {
      fontSize: "15px",
      fontWeight: 500,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#465830",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 500,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#465830",
    },
    p: {
      marginTop: "0",
      marginBottom: "22px",
      textAlign: "justify",
      letterSpacing: "0.6px",
      fontSize: "16px",
      textIndent: "2em",
      lineHeight: "2.1",
    },
    blockquote: {
      borderLeft: "2.5px solid #84a98c",
      padding: "18px 24px",
      margin: "30px 0",
      color: "#52796f",
      fontStyle: "italic",
      letterSpacing: "0.8px",
      lineHeight: "2.0",
      fontSize: "15.5px",
      backgroundColor: "rgba(132, 169, 140, 0.08)",
      borderRadius: "0 6px 6px 0",
    },
    ul: {
      paddingLeft: "2.5em",
      marginBottom: "20px",
      listStyleType: "circle",
    },
    ol: {
      paddingLeft: "2.5em",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      color: "#374334",
      fontSize: "15px",
    },
    a: {
      color: "#2d6a4f",
      textDecoration: "underline",
      textUnderlineOffset: "3px",
      fontWeight: 500,
    },
    strong: {
      color: "#1b4332",
      fontWeight: 600,
    },
    em: {
      fontStyle: "italic",
      color: "#52796f",
    },
    code: {
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      backgroundColor: "#e9edc9",
      color: "#283618",
      padding: "2px 6px",
      borderRadius: "3px",
      fontSize: "0.88em",
    },
    pre: {
      backgroundColor: "#283618",
      color: "#fefae0",
      padding: "20px 24px",
      borderRadius: "8px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.7",
      margin: "24px 0",
    },
    img: {
      maxWidth: "100%",
      borderRadius: "6px",
      margin: "32px auto",
      display: "block",
      boxShadow: "0 8px 24px rgba(40, 54, 24, 0.08)",
    },
    hr: {
      border: "none",
      borderTop: "1px solid #d5dec6",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "26px 0",
      fontSize: "14.5px",
    },
    th: {
      padding: "12px 16px",
      backgroundColor: "#f2f4ec",
      color: "#283618",
      fontWeight: 600,
      textAlign: "left",
      borderBottom: "1.5px solid #84a98c",
    },
    td: {
      padding: "11px 16px",
      borderBottom: "1px solid #e2e8df",
    },
  },
};
