import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const magazine: ThemePreset = {
  id: "magazine",
  name: "杂志风",
  description: "高端生活方式画报排版，艺术波尔多酒红、首字下沉与居中金句",
  tags: ["杂志", "首字下沉", "居中金句", "画报", "复古酒红", "人文散文"],
  cardGradient: ["#fff1f2", "#fecdd3"],
  containerVariant: "magazine-spread",
  banner: {
    type: "none",
  },
  h2Decoration: "magazine-centered",
  quoteStyle: "pull-quote",
  dividerText: "✦   ✦   ✦",
  markHighlight: {
    background: "rgba(244, 63, 94, 0.15)",
    borderBottom: "1.5px solid #e11d48",
    color: "#9f1239",
    padding: "0 4px",
    fontWeight: 700,
  },
  dropcap: {
      marginTop: "0",
    float: "left",
    fontSize: "54px",
    lineHeight: "1.7",
    paddingRight: "12px",
    paddingTop: "4px",
    fontWeight: 800,
    color: "#881337",
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "2.1",
    color: "#27272a",
    backgroundColor: "#fffdfa",
    maxWidth: "720px",
    margin: "0 auto",
    padding: "52px 42px",
    boxShadow: "0 20px 45px -10px rgba(159, 18, 57, 0.08), 0 0 0 1px rgba(0, 0, 0, 0.03)",
    borderRadius: "10px",
  },
  elements: {
    h1: {
      fontSize: "32px",
      fontWeight: 800,
      textAlign: "center",
      marginBottom: "32px",
      color: "#881337",
      letterSpacing: "3px",
      lineHeight: "1.7",
      paddingBottom: "18px",
      borderBottom: "1.5px solid #fecdd3",
    },
    h2: {
      fontSize: "20px",
      fontWeight: 700,
      marginTop: "48px",
      marginBottom: "22px",
      textAlign: "center",
      letterSpacing: "2.5px",
      color: "#881337",
    },
    h3: {
      fontSize: "17px",
      fontWeight: 600,
      marginTop: "30px",
      marginBottom: "14px",
      color: "#4c0519",
      fontStyle: "italic",
    },
    h4: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#4c0519",
    },
    h5: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#4c0519",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#4c0519",
    },
    p: {
      marginTop: "0",
      marginBottom: "22px",
      textAlign: "justify",
      fontSize: "16px",
      letterSpacing: "0.3px",
      color: "#27272a",
      lineHeight: "2.1",
    },
    blockquote: {
      backgroundColor: "rgba(136, 19, 55, 0.04)",
      borderLeft: "none",
      padding: "24px 32px",
      margin: "32px 0",
      borderRadius: "8px",
      color: "#881337",
      fontSize: "16px",
      lineHeight: "1.9",
      fontStyle: "italic",
    },
    ul: {
      paddingLeft: "24px",
      marginBottom: "22px",
      listStyleType: "circle",
    },
    ol: {
      paddingLeft: "24px",
      marginBottom: "22px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      fontSize: "15.5px",
      color: "#27272a",
    },
    a: {
      color: "#881337",
      textDecoration: "underline",
      textUnderlineOffset: "3px",
      fontWeight: 600,
    },
    strong: {
      color: "#881337",
      fontWeight: 800,
    },
    em: {
      fontStyle: "italic",
      color: "#9f1239",
    },
    code: {
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      backgroundColor: "#fff1f2",
      color: "#881337",
      padding: "2px 7px",
      borderRadius: "4px",
      fontSize: "0.88em",
      border: "1px solid #ffe4e6",
    },
    pre: {
      backgroundColor: "#1c1917",
      color: "#f5f5f4",
      padding: "22px 26px",
      borderRadius: "8px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.7",
      margin: "26px 0",
    },
    img: {
      maxWidth: "100%",
      borderRadius: "8px",
      margin: "32px auto",
      display: "block",
      boxShadow: "0 10px 30px rgba(136, 19, 55, 0.08)",
    },
    hr: {
      border: "none",
      borderTop: "1.5px solid #fecdd3",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "26px 0",
      fontSize: "14.5px",
    },
    th: {
      padding: "12px 16px",
      backgroundColor: "#fff1f2",
      color: "#881337",
      fontWeight: 700,
      textAlign: "left",
      borderBottom: "2px solid #881337",
    },
    td: {
      padding: "11px 16px",
      borderBottom: "1px solid #ffe4e6",
    },
  },
};
