import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const modernMinimal: ThemePreset = {
  id: "modern-minimal",
  name: "现代简约",
  description: "瑞士国际主义排版，极简黑白灰阶，克制字距与留白美学",
  tags: ["瑞士风格", "极简", "黑白", "留白", "Medium", "高级感"],
  cardGradient: ["#ffffff", "#e5e7eb"],
  containerVariant: "minimal-flat",
  banner: {
    type: "none",
  },
  h2Decoration: "swiss-block",
  quoteStyle: "default",
  dividerText: "■   ■   ■",
  markHighlight: {
    background: "#18181b",
    color: "#ffffff",
    padding: "1px 6px",
    borderRadius: "2px",
    fontWeight: 700,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "1.9",
    color: "#27272a",
    backgroundColor: "#ffffff",
    maxWidth: "700px",
    margin: "0 auto",
    padding: "52px 42px",
    boxShadow: "0 20px 45px -15px rgba(0, 0, 0, 0.06), 0 0 0 1px rgba(0, 0, 0, 0.04)",
    borderRadius: "10px",
  },
  elements: {
    h1: {
      fontSize: "30px",
      fontWeight: 800,
      color: "#18181b",
      marginBottom: "32px",
      letterSpacing: "-0.5px",
      lineHeight: "1.75",
      paddingBottom: "16px",
      borderBottom: "2px solid #18181b",
    },
    h2: {
      fontSize: "19.5px",
      fontWeight: 700,
      marginTop: "44px",
      marginBottom: "20px",
      color: "#18181b",
      letterSpacing: "-0.3px",
    },
    h3: {
      fontSize: "17px",
      fontWeight: 700,
      marginTop: "28px",
      marginBottom: "12px",
      color: "#27272a",
      letterSpacing: "-0.2px",
    },
    h4: {
      fontSize: "15px",
      fontWeight: 700,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#3f3f46",
    },
    h5: {
      fontSize: "15px",
      fontWeight: 700,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#3f3f46",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 700,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#3f3f46",
    },
    p: {
      marginTop: "0",
      marginBottom: "20px",
      color: "#27272a",
      fontSize: "15.5px",
      textAlign: "left",
      letterSpacing: "0.2px",
      lineHeight: "1.9",
    },
    blockquote: {
      borderLeft: "3.5px solid #18181b",
      padding: "18px 22px",
      margin: "28px 0",
      color: "#3f3f46",
      fontSize: "15px",
      lineHeight: "1.85",
      backgroundColor: "#f9fafb",
      borderRadius: "0 6px 6px 0",
    },
    ul: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "square",
    },
    ol: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      color: "#27272a",
      fontSize: "15px",
    },
    a: {
      color: "#18181b",
      textDecoration: "underline",
      textDecorationThickness: "1.5px",
      textUnderlineOffset: "3px",
      fontWeight: 600,
    },
    strong: {
      fontWeight: 700,
      color: "#18181b",
    },
    em: {
      fontStyle: "italic",
    },
    code: {
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      backgroundColor: "#f4f4f5",
      color: "#18181b",
      padding: "2px 7px",
      fontSize: "0.88em",
      borderRadius: "4px",
      border: "1px solid #e4e4e7",
    },
    pre: {
      backgroundColor: "#18181b",
      color: "#ffffff",
      padding: "20px 24px",
      borderRadius: "8px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.75",
      margin: "26px 0",
    },
    img: {
      maxWidth: "100%",
      margin: "32px auto",
      display: "block",
      borderRadius: "6px",
    },
    hr: {
      border: "none",
      borderTop: "1.5px solid #e4e4e7",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "26px 0",
      fontSize: "14.5px",
    },
    th: {
      padding: "12px 16px",
      backgroundColor: "#f4f4f5",
      color: "#18181b",
      fontWeight: 700,
      textAlign: "left",
      borderBottom: "2px solid #18181b",
    },
    td: {
      padding: "11px 16px",
      borderBottom: "1px solid #e4e4e7",
    },
  },
};
