import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const morandiSoft: ThemePreset = {
  id: "morandi-soft",
  name: "莫兰迪柔调",
  description: "高级低饱和灰调美学，温润豆沙粉与雾霾灰蓝的极致温柔",
  tags: ["莫兰迪", "高级灰", "低饱和", "豆沙粉", "温柔治愈", "美学生活"],
  cardGradient: ["#f5eceb", "#e6edf2"],
  containerVariant: "default",
  banner: {
    type: "none",
  },
  h2Decoration: "morandi-soft",
  quoteStyle: "morandi-card",
  dividerText: "·   ·   ·   ·",
  markHighlight: {
    background: "rgba(180, 142, 148, 0.22)",
    padding: "0 4px",
    color: "#6b4f55",
    fontWeight: 600,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 300,
    fontSize: "15.5px",
    lineHeight: "1.95",
    color: "#3f3f46",
    backgroundColor: "#faf8f7",
    maxWidth: "700px",
    margin: "0 auto",
    padding: "50px 40px",
    borderRadius: "12px",
    boxShadow: "0 20px 45px -15px rgba(107, 79, 85, 0.08), 0 0 0 1px rgba(0, 0, 0, 0.03)",
  },
  elements: {
    h1: {
      fontSize: "27px",
      fontWeight: 600,
      textAlign: "center",
      marginBottom: "32px",
      color: "#5c4046",
      letterSpacing: "1px",
      lineHeight: "1.75",
      paddingBottom: "16px",
      borderBottom: "1.5px solid #e5d5d7",
    },
    h2: {
      fontSize: "19px",
      fontWeight: 600,
      marginTop: "44px",
      marginBottom: "20px",
      color: "#475569",
    },
    h3: {
      fontSize: "16.5px",
      fontWeight: 600,
      marginTop: "28px",
      marginBottom: "12px",
      color: "#6b4f55",
      paddingLeft: "10px",
      borderLeft: "3.5px solid #a88188",
    },
    h4: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#475569",
    },
    h5: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#475569",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#475569",
    },
    p: {
      marginTop: "0",
      marginBottom: "20px",
      fontSize: "15.5px",
      textAlign: "justify",
      letterSpacing: "0.3px",
      color: "#3f3f46",
      lineHeight: "1.9",
    },
    blockquote: {
      backgroundColor: "#f4edeb",
      borderLeft: "3.5px solid #b48e94",
      padding: "18px 24px",
      margin: "26px 0",
      borderRadius: "0 8px 8px 0",
      color: "#5c4046",
      fontSize: "15px",
      lineHeight: "1.85",
    },
    ul: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "circle",
    },
    ol: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      color: "#3f3f46",
      fontSize: "15px",
    },
    a: {
      color: "#6b4f55",
      textDecoration: "underline",
      textUnderlineOffset: "3px",
      fontWeight: 600,
    },
    strong: {
      color: "#5c4046",
      fontWeight: 600,
    },
    em: {
      fontStyle: "italic",
      color: "#6b4f55",
    },
    code: {
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      backgroundColor: "#ede7e5",
      color: "#5c4046",
      padding: "2px 7px",
      borderRadius: "4px",
      fontSize: "0.88em",
    },
    pre: {
      backgroundColor: "#334155",
      color: "#f8fafc",
      padding: "20px 24px",
      borderRadius: "10px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.75",
      margin: "24px 0",
    },
    img: {
      maxWidth: "100%",
      borderRadius: "10px",
      margin: "28px auto",
      display: "block",
      boxShadow: "0 6px 20px rgba(0, 0, 0, 0.05)",
    },
    hr: {
      border: "none",
      borderTop: "1.5px solid #e5d5d7",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "24px 0",
      fontSize: "14.5px",
    },
    th: {
      padding: "12px 16px",
      backgroundColor: "#f2ebe9",
      color: "#5c4046",
      fontWeight: 700,
      textAlign: "left",
      borderBottom: "2px solid #b48e94",
    },
    td: {
      padding: "11px 16px",
      borderBottom: "1px solid #e5d5d7",
    },
  },
};
