import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const neoChinese: ThemePreset = {
  id: "neo-chinese",
  name: "东方雅致",
  description: "新中式东方美学，朱砂印章题签、温润宣纸意境与文人墨色",
  tags: ["新中式", "东方美学", "朱砂印", "宣纸意境", "文化雅致", "宋体"],
  cardGradient: ["#fef2f2", "#fee2e2"],
  containerVariant: "neo-chinese",
  banner: {
    type: "none",
  },
  h2Decoration: "seal-tag",
  quoteStyle: "chinese-scroll",
  dividerText: "❖ ─── ❖ ─── ❖",
  markHighlight: {
    background: "rgba(185, 28, 28, 0.12)",
    borderBottom: "1.5px solid #b91c1c",
    color: "#991b1b",
    padding: "0 3px",
    fontWeight: 700,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "2.15",
    color: "#27272a",
    backgroundColor: "#fcfbf8",
    maxWidth: "720px",
    margin: "0 auto",
    padding: "52px 42px",
    boxShadow: "0 20px 40px -15px rgba(185, 28, 28, 0.05), 0 0 0 1px rgba(0, 0, 0, 0.03)",
    borderRadius: "8px",
  },
  elements: {
    h1: {
      fontSize: "28px",
      fontWeight: 800,
      textAlign: "center",
      marginBottom: "32px",
      color: "#b91c1c",
      letterSpacing: "3.5px",
      lineHeight: "1.7",
      paddingBottom: "16px",
      borderBottom: "1.5px solid #fecaca",
    },
    h2: {
      fontSize: "19px",
      fontWeight: 700,
      marginTop: "44px",
      marginBottom: "20px",
      color: "#b91c1c",
      display: "flex",
      alignItems: "center",
    },
    h3: {
      fontSize: "16.5px",
      fontWeight: 600,
      marginTop: "28px",
      marginBottom: "12px",
      color: "#991b1b",
      paddingLeft: "10px",
      borderLeft: "3.5px solid #b91c1c",
    },
    h4: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#991b1b",
    },
    h5: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#991b1b",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#991b1b",
    },
    p: {
      marginTop: "0",
      marginBottom: "22px",
      textAlign: "justify",
      textIndent: "2em",
      fontSize: "16px",
      letterSpacing: "0.5px",
      color: "#27272a",
      lineHeight: "2.1",
    },
    blockquote: {
      backgroundColor: "#f9f6ef",
      borderLeft: "3.5px solid #b91c1c",
      padding: "20px 26px",
      margin: "28px 0",
      borderRadius: "0 8px 8px 0",
      color: "#451a03",
      fontSize: "15px",
      lineHeight: "1.9",
    },
    ul: {
      paddingLeft: "2.5em",
      marginBottom: "20px",
      listStyleType: "circle",
    },
    ol: {
      paddingLeft: "2.5em",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      color: "#27272a",
      fontSize: "15px",
    },
    a: {
      color: "#b91c1c",
      textDecoration: "underline",
      textUnderlineOffset: "4px",
      fontWeight: 600,
    },
    strong: {
      color: "#991b1b",
      fontWeight: 800,
    },
    em: {
      fontStyle: "italic",
      color: "#b91c1c",
    },
    code: {
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      backgroundColor: "#f5f0e6",
      color: "#991b1b",
      padding: "2px 7px",
      borderRadius: "3px",
      fontSize: "0.88em",
      border: "1px solid #e7ded0",
    },
    pre: {
      backgroundColor: "#1c1917",
      color: "#f5f5f4",
      padding: "20px 24px",
      borderRadius: "6px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.7",
      margin: "26px 0",
    },
    img: {
      maxWidth: "100%",
      borderRadius: "4px",
      margin: "32px auto",
      display: "block",
      border: "1px solid #d4c5b9",
      padding: "5px",
      backgroundColor: "#faf7f2",
      boxShadow: "0 8px 24px rgba(0, 0, 0, 0.06)",
    },
    hr: {
      border: "none",
      borderTop: "1px solid #e7ded0",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "26px 0",
      fontSize: "14.5px",
    },
    th: {
      padding: "12px 16px",
      backgroundColor: "#f5eee1",
      color: "#78350f",
      fontWeight: 700,
      textAlign: "left",
      borderBottom: "2px solid #b91c1c",
    },
    td: {
      padding: "11px 16px",
      borderBottom: "1px solid #e7ded0",
    },
  },
};
