import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const popBrutalism: ThemePreset = {
  id: "pop-brutalism",
  name: "潮流波普",
  description: "新野兽派潮流撞色，纯黑硬边轮廓、明黄微标与潮流态度",
  tags: ["潮流", "新野兽派", "波普撞色", "明黄色", "年轻爆款", "设计先锋"],
  cardGradient: ["#fef08a", "#fde047"],
  containerVariant: "pop-brutalism",
  banner: {
    type: "none",
  },
  h2Decoration: "pop-box",
  quoteStyle: "pop-shadow",
  dividerText: "★ ★ ★ ★ ★",
  markHighlight: {
    background: "#fef08a",
    border: "1.5px solid #000000",
    boxShadow: "1.5px 1.5px 0 #000000",
    color: "#000000",
    padding: "1px 5px",
    fontWeight: 800,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 600,
    fontSize: "15.5px",
    lineHeight: "1.9",
    color: "#09090b",
    backgroundColor: "#ffffff",
    maxWidth: "700px",
    margin: "0 auto",
    padding: "48px 38px",
    borderRadius: "10px",
    border: "2px solid #000000",
    boxShadow: "5px 5px 0px #000000",
  },
  elements: {
    h1: {
      fontSize: "30px",
      fontWeight: 900,
      textAlign: "center",
      marginBottom: "30px",
      color: "#000000",
      letterSpacing: "-0.5px",
      lineHeight: "1.75",
      paddingBottom: "16px",
      borderBottom: "3px solid #000000",
    },
    h2: {
      fontSize: "19px",
      fontWeight: 800,
      marginTop: "44px",
      marginBottom: "20px",
      color: "#000000",
    },
    h3: {
      fontSize: "16.5px",
      fontWeight: 800,
      marginTop: "28px",
      marginBottom: "12px",
      color: "#000000",
      display: "inline-block",
      borderBottom: "2.5px solid #eab308",
      paddingBottom: "2px",
    },
    h4: {
      fontSize: "15px",
      fontWeight: 700,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#000000",
    },
    h5: {
      fontSize: "15px",
      fontWeight: 700,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#000000",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 700,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#000000",
    },
    p: {
      marginTop: "0",
      marginBottom: "20px",
      fontSize: "15.5px",
      textAlign: "justify",
      letterSpacing: "0.2px",
      color: "#18181b",
      lineHeight: "1.9",
    },
    blockquote: {
      backgroundColor: "#fef9c3",
      border: "2px solid #000000",
      boxShadow: "3.5px 3.5px 0px #000000",
      padding: "18px 24px",
      margin: "28px 0",
      borderRadius: "4px",
      color: "#000000",
      fontSize: "15px",
      lineHeight: "1.85",
      fontWeight: 500,
    },
    ul: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "square",
    },
    ol: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      color: "#18181b",
      fontSize: "15px",
    },
    a: {
      color: "#000000",
      backgroundColor: "#fef08a",
      padding: "0 3px",
      borderBottom: "2px solid #000000",
      fontWeight: 700,
      textDecoration: "none",
    },
    strong: {
      color: "#000000",
      fontWeight: 900,
      backgroundColor: "#fef08a",
      padding: "0 3px",
    },
    em: {
      fontStyle: "italic",
    },
    code: {
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      backgroundColor: "#f4f4f5",
      color: "#000000",
      padding: "2px 7px",
      border: "1.5px solid #000000",
      fontWeight: 600,
      fontSize: "0.88em",
    },
    pre: {
      backgroundColor: "#000000",
      color: "#ffffff",
      padding: "20px 24px",
      border: "2px solid #000000",
      boxShadow: "4px 4px 0px #eab308",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.7",
      margin: "24px 0",
    },
    img: {
      maxWidth: "100%",
      borderRadius: "0px",
      border: "2px solid #000000",
      boxShadow: "5px 5px 0px #000000",
      margin: "30px auto",
      display: "block",
    },
    hr: {
      border: "none",
      borderTop: "3px solid #000000",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "26px 0",
      fontSize: "14.5px",
      border: "2px solid #000000",
      boxShadow: "4px 4px 0px #000000",
    },
    th: {
      padding: "12px 16px",
      backgroundColor: "#000000",
      color: "#ffffff",
      fontWeight: 800,
      textAlign: "left",
      borderRight: "1px solid #3f3f46",
    },
    td: {
      padding: "11px 16px",
      borderBottom: "1.5px solid #000000",
      borderRight: "1.5px solid #000000",
    },
  },
};
