import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const retroNewspaper: ThemePreset = {
  id: "retro-newspaper",
  name: "复古报纸",
  description: "百年老报通栏版式，双重粗细报头框线与铅印社论风格",
  tags: ["报纸", "复古", "铅印", "社论", "民国风", "人文历史"],
  cardGradient: ["#fef9c3", "#d6d3d1"],
  containerVariant: "newspaper-frame",
  banner: {
    type: "none",
  },
  h2Decoration: "newspaper-banner",
  quoteStyle: "newspaper-clip",
  dividerText: "═   ❖   ═",
  markHighlight: {
    background: "#e7e5e4",
    padding: "0 4px",
    color: "#1c1917",
    fontWeight: 700,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "2.1",
    color: "#292524",
    backgroundColor: "#faf6ee",
    maxWidth: "710px",
    margin: "0 auto",
    padding: "52px 42px",
    boxShadow: "0 15px 35px rgba(68, 64, 60, 0.08), 0 0 0 1px rgba(68, 64, 60, 0.04)",
    borderRadius: "6px",
  },
  elements: {
    h1: {
      fontSize: "30px",
      fontWeight: 900,
      textAlign: "center",
      marginBottom: "28px",
      color: "#1c1917",
      letterSpacing: "3px",
      lineHeight: "1.75",
      paddingBottom: "16px",
      borderBottom: "2px solid #1c1917",
    },
    h2: {
      fontSize: "19px",
      fontWeight: 800,
      marginTop: "44px",
      marginBottom: "20px",
      color: "#1c1917",
      textAlign: "center",
      letterSpacing: "2px",
      padding: "6px 14px",
      borderTop: "1px solid #78716c",
      borderBottom: "1px solid #78716c",
      backgroundColor: "rgba(120, 113, 108, 0.08)",
    },
    h3: {
      fontSize: "17px",
      fontWeight: 700,
      marginTop: "28px",
      marginBottom: "12px",
      color: "#292524",
      borderLeft: "3.5px solid #1c1917",
      paddingLeft: "10px",
    },
    h4: {
      fontSize: "16px",
      fontWeight: 700,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#292524",
    },
    h5: {
      fontSize: "15.5px",
      fontWeight: 700,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#292524",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 700,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#292524",
    },
    p: {
      marginTop: "0",
      marginBottom: "20px",
      textAlign: "justify",
      textIndent: "2em",
      fontSize: "16px",
      letterSpacing: "0.3px",
      lineHeight: "2.1",
      color: "#292524",
    },
    blockquote: {
      border: "1px solid #a8a29e",
      backgroundColor: "rgba(68, 64, 60, 0.04)",
      padding: "18px 24px",
      margin: "28px 0",
      color: "#44403c",
      fontSize: "15px",
      lineHeight: "1.9",
      fontStyle: "italic",
    },
    ul: {
      paddingLeft: "2.5em",
      marginBottom: "20px",
      listStyleType: "square",
    },
    ol: {
      paddingLeft: "2.5em",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      color: "#292524",
      fontSize: "15px",
    },
    a: {
      color: "#1c1917",
      textDecoration: "underline",
      textUnderlineOffset: "3px",
      fontWeight: 700,
    },
    strong: {
      fontWeight: 800,
      color: "#1c1917",
    },
    em: {
      fontStyle: "italic",
    },
    code: {
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      backgroundColor: "#ece5d8",
      color: "#1c1917",
      padding: "2px 6px",
      fontSize: "0.88em",
      border: "1px solid #d6cebf",
    },
    pre: {
      backgroundColor: "#1c1917",
      color: "#f5f5f4",
      padding: "20px 24px",
      borderRadius: "4px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.75",
      margin: "26px 0",
    },
    img: {
      maxWidth: "100%",
      margin: "32px auto",
      display: "block",
      border: "1px solid #a8a29e",
    },
    hr: {
      border: "none",
      borderTop: "1.5px solid #78716c",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "26px 0",
      fontSize: "14.5px",
      border: "1px solid #78716c",
    },
    th: {
      padding: "11px 16px",
      backgroundColor: "#ece5d8",
      color: "#1c1917",
      fontWeight: 800,
      textAlign: "left",
      borderBottom: "1.5px solid #78716c",
    },
    td: {
      padding: "10px 16px",
      borderBottom: "1px solid #d6cebf",
    },
  },
};
