import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const techFuture: ThemePreset = {
  id: "tech-future",
  name: "科技未来",
  description: "前沿科技全息美学，流光渐变、深空矩阵与赛博霓虹质感",
  tags: ["科技", "未来", "全息渐变", "深空黑", "前沿AI", "数字前沿"],
  cardGradient: ["#180b2b", "#061325"],
  containerVariant: "tech-cyber-glow",
  banner: {
    type: "none",
  },
  h2Decoration: "cyber-glow",
  quoteStyle: "cyber-card",
  dividerText: "✦ ─── ❖ ─── ✦",
  markHighlight: {
    background: "rgba(168, 85, 247, 0.28)",
    borderBottom: "2px solid #c084fc",
    color: "#f0abfc",
    padding: "0 4px",
    fontWeight: 700,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 400,
    fontSize: "15.5px",
    lineHeight: "1.9",
    color: "#e2e8f0",
    backgroundColor: "#090d16",
    maxWidth: "720px",
    margin: "0 auto",
    padding: "50px 40px",
    borderRadius: "14px",
    border: "1px solid rgba(99, 102, 241, 0.25)",
    boxShadow: "0 0 35px -5px rgba(99, 102, 241, 0.15)",
  },
  elements: {
    h1: {
      fontSize: "30px",
      fontWeight: 800,
      textAlign: "center",
      marginBottom: "32px",
      color: "#38bdf8",
      letterSpacing: "1px",
      lineHeight: "1.7",
      paddingBottom: "16px",
      borderBottom: "1px solid rgba(56, 189, 248, 0.3)",
    },
    h2: {
      fontSize: "19.5px",
      fontWeight: 700,
      marginTop: "44px",
      marginBottom: "20px",
      color: "#38bdf8",
      display: "flex",
      alignItems: "center",
    },
    h3: {
      fontSize: "16.5px",
      fontWeight: 600,
      marginTop: "28px",
      marginBottom: "12px",
      color: "#c084fc",
    },
    h4: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#818cf8",
    },
    h5: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#818cf8",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#818cf8",
    },
    p: {
      marginTop: "0",
      marginBottom: "20px",
      color: "#cbd5e1",
      fontSize: "15.5px",
      textAlign: "justify",
      letterSpacing: "0.3px",
      lineHeight: "1.9",
    },
    blockquote: {
      backgroundColor: "rgba(30, 27, 75, 0.45)",
      borderLeft: "3.5px solid #818cf8",
      padding: "18px 24px",
      margin: "26px 0",
      borderRadius: "0 8px 8px 0",
      color: "#c7d2fe",
      fontSize: "15px",
      lineHeight: "1.85",
    },
    ul: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "circle",
    },
    ol: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      color: "#cbd5e1",
      fontSize: "15px",
    },
    a: {
      color: "#38bdf8",
      textDecoration: "underline",
      textUnderlineOffset: "3px",
      fontWeight: 600,
    },
    strong: {
      color: "#f8fafc",
      fontWeight: 700,
    },
    em: {
      fontStyle: "italic",
      color: "#38bdf8",
    },
    code: {
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      backgroundColor: "rgba(30, 27, 75, 0.7)",
      color: "#38bdf8",
      padding: "2px 7px",
      borderRadius: "4px",
      fontSize: "0.88em",
      border: "1px solid rgba(99, 102, 241, 0.3)",
    },
    pre: {
      backgroundColor: "#030712",
      color: "#f8fafc",
      padding: "20px 24px",
      borderRadius: "10px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.7",
      margin: "24px 0",
      border: "1px solid rgba(99, 102, 241, 0.3)",
    },
    img: {
      maxWidth: "100%",
      borderRadius: "10px",
      margin: "30px auto",
      display: "block",
      border: "1px solid rgba(99, 102, 241, 0.3)",
      boxShadow: "0 0 25px rgba(56, 189, 248, 0.15)",
    },
    hr: {
      border: "none",
      borderTop: "1px solid rgba(99, 102, 241, 0.3)",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "26px 0",
      fontSize: "14.5px",
      border: "1px solid rgba(99, 102, 241, 0.2)",
    },
    th: {
      padding: "12px 16px",
      backgroundColor: "rgba(30, 27, 75, 0.6)",
      color: "#38bdf8",
      fontWeight: 700,
      textAlign: "left",
      borderBottom: "1.5px solid rgba(99, 102, 241, 0.4)",
    },
    td: {
      padding: "11px 16px",
      borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
      color: "#cbd5e1",
    },
  },
};
