import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const warmJournal: ThemePreset = {
  id: "warm-journal",
  name: "温暖手帐",
  description: "日系温馨手记，暖阳枫叶橙、治愈米白与生活随笔美学",
  tags: ["手帐", "治愈", "暖杏色", "温馨生活", "日系日常", "随笔"],
  cardGradient: ["#ffedd5", "#fed7aa"],
  containerVariant: "journal-notebook",
  banner: {
    type: "none",
  },
  h2Decoration: "journal-sticker",
  quoteStyle: "post-it",
  dividerText: "✦   ✧   ✦",
  markHighlight: {
    background: "linear-gradient(to top, rgba(251, 146, 60, 0.45) 45%, transparent 45%)",
    padding: "0 4px",
    borderRadius: "2px",
    color: "#9a3412",
    fontWeight: 700,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 400,
    fontSize: "15.5px",
    lineHeight: "1.95",
    color: "#573a27",
    backgroundColor: "#fffdf9",
    maxWidth: "680px",
    margin: "0 auto",
    padding: "48px 36px",
    borderRadius: "12px",
    boxShadow: "0 15px 35px -5px rgba(251, 146, 60, 0.08), 0 0 0 1px rgba(251, 146, 60, 0.03)",
  },
  elements: {
    h1: {
      fontSize: "26px",
      fontWeight: 800,
      textAlign: "center",
      color: "#c2410c",
      marginBottom: "32px",
      letterSpacing: "1px",
      lineHeight: "1.75",
      paddingBottom: "14px",
      borderBottom: "1.5px solid #fed7aa",
    },
    h2: {
      fontSize: "18.5px",
      fontWeight: 700,
      marginTop: "42px",
      marginBottom: "20px",
      color: "#c2410c",
    },
    h3: {
      fontSize: "16px",
      fontWeight: 600,
      marginTop: "26px",
      marginBottom: "12px",
      color: "#ea580c",
      paddingLeft: "10px",
      borderLeft: "3.5px solid #fb923c",
    },
    h4: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "18px",
      marginBottom: "6px",
      color: "#ea580c",
    },
    h5: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "18px",
      marginBottom: "6px",
      color: "#ea580c",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "18px",
      marginBottom: "6px",
      color: "#ea580c",
    },
    p: {
      marginTop: "0",
      marginBottom: "20px",
      fontSize: "15.5px",
      textAlign: "justify",
      letterSpacing: "0.3px",
      color: "#573a27",
      lineHeight: "1.95",
    },
    blockquote: {
      backgroundColor: "#fff7ed",
      borderLeft: "3.5px solid #ea580c",
      padding: "18px 22px",
      margin: "24px 0",
      borderRadius: "0 8px 8px 0",
      color: "#7c2d12",
      fontSize: "15px",
      lineHeight: "1.85",
    },
    ul: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "circle",
    },
    ol: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      color: "#573a27",
      fontSize: "15px",
    },
    a: {
      color: "#c2410c",
      textDecoration: "underline",
      textUnderlineOffset: "3px",
      fontWeight: 600,
    },
    strong: {
      color: "#9a3412",
      fontWeight: 700,
    },
    em: {
      fontStyle: "italic",
      color: "#c2410c",
    },
    code: {
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      backgroundColor: "#ffedd5",
      color: "#9a3412",
      padding: "2px 6px",
      borderRadius: "4px",
      fontSize: "0.88em",
      border: "1px solid #fed7aa",
    },
    pre: {
      backgroundColor: "#431407",
      color: "#ffedd5",
      padding: "20px 24px",
      borderRadius: "10px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.75",
      margin: "24px 0",
    },
    img: {
      maxWidth: "100%",
      borderRadius: "6px",
      margin: "28px auto",
      display: "block",
      border: "1px solid #fde68a",
      padding: "6px",
      backgroundColor: "#ffffff",
      boxShadow: "0 6px 20px rgba(251, 146, 60, 0.15)",
    },
    hr: {
      border: "none",
      borderTop: "1.5px dashed #fed7aa",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "24px 0",
      fontSize: "14.5px",
    },
    th: {
      padding: "12px 16px",
      backgroundColor: "#ffedd5",
      color: "#7c2d12",
      fontWeight: 700,
      textAlign: "left",
      borderBottom: "2px solid #ea580c",
    },
    td: {
      padding: "11px 16px",
      borderBottom: "1px solid #fed7aa",
    },
  },
};
