import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const warmLatte: ThemePreset = {
  id: "warm-latte",
  name: "暖阳拿铁",
  description: "焦糖咖啡与燕麦暖棕，午后阳光斜照的咖啡馆慢读美学",
  tags: ["拿铁棕", "咖啡馆", "慢生活", "焦糖暖色", "生活美学", "温馨手作"],
  cardGradient: ["#fef3c7", "#fed7aa"],
  containerVariant: "latte-soft",
  banner: {
    type: "none",
  },
  h2Decoration: "latte-badge",
  quoteStyle: "latte-card",
  dividerText: "☕ ─── ✦ ─── ☕",
  markHighlight: {
    background: "rgba(180, 83, 9, 0.18)",
    padding: "0 4px",
    color: "#78350f",
    fontWeight: 700,
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "2.1",
    color: "#451a03",
    backgroundColor: "#fdfbf7",
    maxWidth: "700px",
    margin: "0 auto",
    padding: "50px 40px",
    borderRadius: "12px",
    boxShadow: "0 20px 45px -12px rgba(120, 53, 15, 0.08), 0 0 0 1px rgba(0, 0, 0, 0.02)",
  },
  elements: {
    h1: {
      fontSize: "28px",
      fontWeight: 800,
      textAlign: "center",
      marginBottom: "32px",
      color: "#78350f",
      letterSpacing: "1.5px",
      lineHeight: "1.7",
      paddingBottom: "16px",
      borderBottom: "1.5px solid #fde68a",
    },
    h2: {
      fontSize: "19px",
      fontWeight: 700,
      marginTop: "44px",
      marginBottom: "20px",
      color: "#92400e",
      display: "flex",
      alignItems: "center",
    },
    h3: {
      fontSize: "16.5px",
      fontWeight: 600,
      marginTop: "28px",
      marginBottom: "12px",
      color: "#b45309",
      paddingLeft: "10px",
      borderLeft: "3.5px solid #d97706",
    },
    h4: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#92400e",
    },
    h5: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#92400e",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#92400e",
    },
    p: {
      marginTop: "0",
      marginBottom: "20px",
      textAlign: "justify",
      fontSize: "15.5px",
      letterSpacing: "0.4px",
      color: "#451a03",
      lineHeight: "2.1",
    },
    blockquote: {
      backgroundColor: "#faf2e7",
      borderLeft: "3.5px solid #b45309",
      padding: "18px 24px",
      margin: "26px 0",
      borderRadius: "0 8px 8px 0",
      color: "#78350f",
      fontSize: "15px",
      lineHeight: "1.85",
    },
    ul: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "circle",
    },
    ol: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      color: "#451a03",
      fontSize: "15px",
    },
    a: {
      color: "#b45309",
      textDecoration: "underline",
      textUnderlineOffset: "3px",
      fontWeight: 600,
    },
    strong: {
      color: "#78350f",
      fontWeight: 700,
    },
    em: {
      fontStyle: "italic",
      color: "#92400e",
    },
    code: {
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      backgroundColor: "#fef3c7",
      color: "#78350f",
      padding: "2px 7px",
      borderRadius: "4px",
      fontSize: "0.88em",
      border: "1px solid #fde68a",
    },
    pre: {
      backgroundColor: "#292524",
      color: "#fef3c7",
      padding: "20px 24px",
      borderRadius: "8px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.7",
      margin: "24px 0",
    },
    img: {
      maxWidth: "100%",
      borderRadius: "12px",
      margin: "28px auto",
      display: "block",
      boxShadow: "0 8px 24px rgba(180, 83, 9, 0.1)",
    },
    hr: {
      border: "none",
      borderTop: "1.5px solid #fde68a",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "24px 0",
      fontSize: "14.5px",
    },
    th: {
      padding: "12px 16px",
      backgroundColor: "#fef3c7",
      color: "#78350f",
      fontWeight: 700,
      textAlign: "left",
      borderBottom: "2px solid #b45309",
    },
    td: {
      padding: "11px 16px",
      borderBottom: "1px solid #fed7aa",
    },
  },
};
