import { ThemePreset, WECHAT_OFFICIAL_FONT_FAMILY, WECHAT_MONOSPACE_FONT_FAMILY } from "../types";

export const wechat: ThemePreset = {
  id: "wechat",
  name: "公众号风",
  description: "新媒体排版典范，翡翠绿胶囊徽章与荧光笔划线标记",
  tags: ["公众号", "新媒体", "荧光笔", "胶囊徽章", "清新自然"],
  cardGradient: ["#ecfdf5", "#a7f3d0"],
  containerVariant: "default",
  banner: {
    type: "none",
  },
  h2Decoration: "wechat-badge",
  quoteStyle: "wechat-bubble",
  dividerText: "◆   ◆   ◆",
  markHighlight: {
    background: "linear-gradient(to top, rgba(253, 224, 71, 0.75) 45%, transparent 45%)",
    padding: "0 4px",
    borderRadius: "2px",
    fontWeight: 700,
    color: "#0f172a",
  },
  container: {
    fontFamily: WECHAT_OFFICIAL_FONT_FAMILY,
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "1.9",
    color: "#27272a",
    backgroundColor: "#ffffff",
    maxWidth: "680px",
    margin: "0 auto",
    padding: "48px 36px",
    boxShadow: "0 20px 40px -15px rgba(5, 150, 105, 0.08), 0 0 0 1px rgba(0, 0, 0, 0.03)",
    borderRadius: "12px",
  },
  elements: {
    h1: {
      fontSize: "26px",
      fontWeight: 800,
      textAlign: "center",
      marginBottom: "32px",
      color: "#0f172a",
      lineHeight: "1.7",
      letterSpacing: "0.5px",
      paddingBottom: "16px",
      borderBottom: "1.5px dashed #a7f3d0",
    },
    h2: {
      fontSize: "19px",
      fontWeight: 700,
      marginTop: "42px",
      marginBottom: "20px",
      color: "#065f46",
    },
    h3: {
      fontSize: "16.5px",
      fontWeight: 600,
      marginTop: "28px",
      marginBottom: "14px",
      color: "#047857",
      paddingLeft: "10px",
      borderLeft: "3.5px solid #10b981",
    },
    h4: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#065f46",
    },
    h5: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#065f46",
    },
    h6: {
      fontSize: "15px",
      fontWeight: 600,
      marginTop: "20px",
      marginBottom: "8px",
      color: "#065f46",
    },
    p: {
      marginTop: "0",
      marginBottom: "20px",
      fontSize: "15.5px",
      textAlign: "justify",
      letterSpacing: "0.4px",
      color: "#374151",
      lineHeight: "1.9",
    },
    blockquote: {
      backgroundColor: "rgba(16, 185, 129, 0.06)",
      borderLeft: "3.5px solid #10b981",
      padding: "18px 22px",
      margin: "26px 0",
      borderRadius: "0 8px 8px 0",
      color: "#1f2937",
      fontSize: "15px",
      lineHeight: "1.85",
    },
    ul: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "circle",
    },
    ol: {
      paddingLeft: "24px",
      marginBottom: "20px",
      listStyleType: "decimal",
    },
    li: {
      marginBottom: "8px",
      fontSize: "15px",
      color: "#374151",
    },
    a: {
      color: "#059669",
      textDecoration: "underline",
      textUnderlineOffset: "3px",
      fontWeight: 600,
    },
    strong: {
      color: "#0f172a",
      fontWeight: 700,
    },
    em: {
      fontStyle: "italic",
      color: "#047857",
    },
    code: {
      backgroundColor: "#ecfdf5",
      color: "#065f46",
      padding: "2px 8px",
      borderRadius: "4px",
      fontSize: "0.88em",
      fontFamily: WECHAT_MONOSPACE_FONT_FAMILY,
      border: "1px solid #d1fae5",
    },
    pre: {
      backgroundColor: "#1e293b",
      color: "#f8fafc",
      padding: "22px 24px",
      borderRadius: "10px",
      overflow: "auto",
      fontSize: "13.5px",
      lineHeight: "1.7",
      margin: "24px 0",
      border: "1px solid #334155",
      boxShadow: "0 4px 16px rgba(0, 0, 0, 0.08)",
    },
    img: {
      maxWidth: "100%",
      borderRadius: "10px",
      margin: "28px auto",
      display: "block",
      boxShadow: "0 6px 20px rgba(0,0,0,0.08)",
    },
    hr: {
      border: "none",
      borderTop: "1.5px dashed #a7f3d0",
      margin: "36px 0",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      margin: "24px 0",
      fontSize: "14.5px",
    },
    th: {
      padding: "12px 16px",
      backgroundColor: "#ecfdf5",
      color: "#065f46",
      fontWeight: 700,
      textAlign: "left",
      borderBottom: "2px solid #10b981",
    },
    td: {
      padding: "12px 16px",
      borderBottom: "1px solid #e5e7eb",
    },
  },
};
